### ISSUE TITLE
tmux hook can't be removed.

### ISSUE THREAD

**Issue by kevinhwang91** [seebye/ueberzug#117]
I posted the issue in tmux not long ago. https://github.com/tmux/tmux/issues/2338

It seems that the tmux session hooks can't be removed properly.

**Comment by kevinhwang91** [comment]
I can reproduce by running ranger preview image from ueberzug inside neovim internal terminal.

**Comment by seebye** [comment]
1. I don't get the relation between this and tmux stops to work as expected.  
Even if there is an hook which instructs tmux to run a program if a certain event occurs tmux should still send the toggle pane-focus events.  
2. I guess you checked that these processes don't run anymore.  
In certain circumstances hooks won't be cleaned up.  
E.g. if ueberzug gets killed which should be for example the case if you run out of ram or if it needs more than a second to exit.  
This was implemented due to an not reproducible error https://github.com/ranger/ranger/pull/1284#issuecomment-419544108

**Comment by kevinhwang91** [comment]
1. I haven't dived into the source code of tmux, but I guess that there are some conflicting issues between global and session hook.

2. Yes, the processes recorded in tmux hooks are killed. I don't know why https://github.com/seebye/ueberzug/blob/7df7f182aaff033a6a66395d2ab2876e72e07cc3/ueberzug/layer.py#L216 is necessary.
I occasionally encountered some ueberzug processes to be orphaned after I previewed images in ranger and then exit, although I ran ranger as a child process of zsh inside tmux. (the processes recorded in tmux hooks are killed)
