### ISSUE TITLE
Support svg

### ISSUE THREAD

**Issue by seebye** [seebye/ueberzug#21]
Support svg files by using https://github.com/deeplook/svglib  
(and? https://pillow.readthedocs.io/en/stable/handbook/writing-your-own-file-decoder.html#writing-your-own-file-decoder-in-python )

**Comment by sergarcia** [comment]
I use ueberzug for file preview in vifm. As a work-around to preview .svg I convert them .png. I use a buffer to only do such conversion when  the .svg file changes. The method is quite fast, in fact the previews with this method render faster than large .png files.  Here is the relevant section of my image preview script: 
~~~
file="$6"
filepath=${PWD}/$file
filename=$(basename -- "$file")
extension="${filename##*.}"

if [ "$extension" = "svg" ]; then
# check buffer and convert if png does not exist or svg has been changed after png was created
	filepath="$HOME/.imgbuffer/$(basename "$filename" .svg).png"
	if [ -f $filepath ]; then
		lastsvgmod=$(date +%s -r "$file")
		lastpngmod=$(date +%s -r "$filepath")
		if [ $(($lastsvgmod - $lastpngmod)) -gt 20 ]; then
			inkscape -z -C -d=50 --file="$filename" --export-png="$filepath" &> /dev/null
		fi
	else
		inkscape -z -C -d=50 --file="$filename" --export-png="$filepath" &> /dev/null
	fi
fi

if [ "$extension" = "pdf" ]; then
# In the case of pdf buffering is not needed due to the speed of ghostscript
	filepath="/tmp/$(basename "$filename" .pdf).png"
	gs -dNOPAUSE -dBATCH -dFirstPage=1 -dLastPage=1 -sDEVICE=png16m -r200 -sOutputFile="$filepath" "$filename" &> /dev/null
fi

~~~

(I added pdf preview as a bonus)

**Comment by seebye** [comment]
@sergarcia I think your comment fits better to the https://github.com/cirala/vifmimg repository.

**Comment by sergarcia** [comment]
@seebye Thanks for the suggestion, I was not familiar with that repo!
