### ISSUE TITLE
Dependencies for ueberzug

### ISSUE THREAD

**Issue by ddmin** [seebye/ueberzug#50]
I don't think it's very clear what dependencies this program requires. I think this should be explicitly stated in the README or somewhere else.

From my experience I had to install
* ibjpeg8-dev
* zlib1g-dev
* python-dev
* python3-dev
* libxtst-dev

**Comment by seebye** [comment]
I partly agree.  

- python3 header files & libraries
- X11 header files & libraries
- Xext header files & libraries

are required to build ueberzug's c module and should be mentioned.  
The rest are indirect dependencies e.g. dependencies to compile pillow.

**Comment by Maltimore** [comment]
I'm reviving this old issue, because it took me quite a while to understand how to install ranger.

On ubuntu I had to install ```libxtst-dev``` and ```libx11-dev``` to get the necessary dependencies. This is not obvious. I have no idea what Xext is, for instance. I think just mentioning this directly would save people a lot of time.
